### ISSUE TITLE
Model training differences

### ISSUE THREAD

**Issue by wq577-lab** [maxiuw/UADA3D#5]
Hi, I tried to use the model and yaml file centerpoint-M-downsampling you provided, and experimented on cs64 and cs16,
![image](https://github.com/user-attachments/assets/1f059d24-dd89-402a-847f-d1dc99a04a64)
The results of the model you provided are different from the results I trained myself using the same yaml.
Here are the results of my test with the provided pth
![image](https://github.com/user-attachments/assets/0f3e43d2-6a32-4d6e-9e23-9848a1c51617)
Here are the results in the log you gave:
![image](https://github.com/user-attachments/assets/001e1d7e-b51d-4255-b908-248182361c00)
The two results are very different. The training configuration used is the default one in yaml, the batch size is 4, and the CS64 and CS16 datasets are downloaded from the official website. I have observed a problem. The number of VLD32 datasets (19537) you provided in OneDrive is different from the 14000 provided by the official website. Did you do anything with the data? I hope you can answer my question. Thank you very much and look forward to your reply!

**Comment by maxiuw** [comment]
#6
