### ISSUE TITLE
CS64_CS16 downsampling issue

### ISSUE THREAD

**Issue by wq577-lab** [maxiuw/UADA3D#6]
Hello, I found that in the weights and yaml provided, all the configurations in centerpoint-M.yaml and centerpoint-M-downsampling.yaml are the same, but the final AP is much different. I feel that the only difference is downsampling. I understand that it is a downsampling data enhancement from CS64->CS16. Please answer my confusion. If there is a similar downsampling operation, is it offline or online? If it is online, please tell me the specific location of the code
![image](https://github.com/user-attachments/assets/922c51a6-dc5e-4650-8269-71147d56cf75)
![image](https://github.com/user-attachments/assets/87c4bdab-3d12-42e1-bc66-db63151dc915)

**Comment by maxiuw** [comment]
Hi 
We do down sampling and ROS for individual objects (not the same for all the objects as previous works). DS helps a lot so I would definitely recommend doing that, as we explained in the paper it bridges the initial domain gap. 
I recommend reading the paper and following our data augmentation process :)

**Comment by wq577-lab** [comment]
Thank you for your prompt reply. I don't know how to do downsampling in the code. Can you provide me with the corresponding code? Thank you very much.

**Comment by wq577-lab** [comment]
> 您好， 我们对单个对象进行下采样和 ROS（与以前的工作不同，对所有对象都一样）。DS 有很大帮助，所以我绝对建议这样做，正如我们在论文中解释的那样，它弥补了最初的领域差距。 我建议阅读论文并遵循我们的数据增强过程 :)






> Hi We do down sampling and ROS for individual objects (not the same for all the objects as previous works). DS helps a lot so I would definitely recommend doing that, as we explained in the paper it bridges the initial domain gap. I recommend reading the paper and following our data augmentation process :)

Thank you for your prompt reply. I don't know how to do downsampling in the code. Can you provide me with the corresponding code? Thank you very much.

**Comment by wq577-lab** [comment]
> Hi We do down sampling and ROS for individual objects (not the same for all the objects as previous works). DS helps a lot so I would definitely recommend doing that, as we explained in the paper it bridges the initial domain gap. I recommend reading the paper and following our data augmentation process :)

Thank you for your prompt reply. I don't know how to do downsampling in the code. Can you provide me with the corresponding code? Thank you very much.

**Comment by maxiuw** [comment]
Hi, I can't find it at the moment. You would need to implement it yourself. It is not that hard, but it is not that easy, I would say. 
In downsampling you need to iterate over points, understand to which lidar layer they belong to and then remove that point (e.g if you go from 32 to 16, then you need to remove every 2nd layer).

**Comment by wq577-lab** [comment]
> Hi, I can't find it at the moment. You would need to implement it yourself. It is not that hard, but it is not that easy, I would say. In downsampling you need to iterate over points, understand to which lidar layer they belong to and then remove that point (e.g if you go from 32 to 16, then you need to remove every 2nd layer).

Thank you very much for your reply, I have implemented it myself
