### ISSUE TITLE
one-drive data files 

### ISSUE THREAD

**Issue by LeftThink** [maxiuw/UADA3D#8]
hello, I previously saw models, logs, and some data files stored in OneDrive, but now they are all gone from OneDrive. Has it been closed or made unavailable?

**Comment by maxiuw** [comment]
hi, yes, we are cleaning some since I realized not all the models there were the ones we used for evaluation and some others were missing. I am working on different projects atm, I upload all of the stuff again when ready. If you need something specific shoot me an email and ill try to respond asap
